on:
  push:
    branches:
      - main

permissions: read-all

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-lates
    permissions:
      contents: write
      pull-requests: writes
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: simple
